     
version: '3.1'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3306/login_system
    restart: on-failure

  db:
    image: mysql:latest
    environment:
      MYSQL_USER : spring
      MYSQL_PASSWORD : '1234'
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: login_system
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10